export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  readTime: string;
  category: string;
  body: string[];
};

export const posts: Post[] = [
  {
    slug: "yes-i-understand-lie-class-echo",
    title: "The \"Yes, I Understand\" Lie: Why I Started Building Class Echo to Save My Teaching Sanity",
    excerpt: "Most students pretend they understand to avoid embarrassment. I built Class Echo to create a safe space for honest feedback without the performance anxiety.",
    date: "2026-05-29",
    readTime: "5 min read",
    category: "Building Products",
    body: [
      "Picture this: you're standing in front of a classroom, pouring your heart and soul into explaining a complex tech concept something like asynchronous data fetching or nested React state management.",
      "You pause, take a sip of water, look around the room, and ask the ultimate forbidden question:",
      "\"Does everyone understand so far?\"",
      "Right on cue, the entire class gives you synchronized nods. \"Yes, instructor.\" \"We understand.\" \"Everything is fine.\"",
      "Spoiler alert: they absolutely did not understand. In reality, most of them were completely lost.",
      "As a facilitator at Harley Innovations Hub, I ran into this problem very early. I could see the confusion on some faces, but publicly, the response was always positive. That's when I realized something important about classroom psychology: Students will often pretend they understand just to avoid being the only person admitting they are confused. Nobody wants to raise their hand at 4:30 PM and say, \"I have no idea what's going on.\"",
      "The problem is, without an honest and safe feedback system, teaching starts to feel like operating in the dark. You can't improve a lesson if you don't know where students are struggling. So, being a frontend engineer, I did what any developer would do when faced with a communication problem: I opened VS Code and started building a solution. I call it Class Echo.",
      "Moving From Vague Nods to Real Feedback",
      "The philosophy behind Class Echo is simple: remove friction. I didn't want to create another bloated learning management system with long signup processes and unnecessary complexity. If students need to create an account just to say \"the class is moving too fast,\" most of them simply won't bother.",
      "Instead, Class Echo allows instructors to generate a quick link where students can anonymously submit feedback in real time. To make the feedback actually useful, I avoided generic questions like \"How was class today?\" and focused on six specific areas instead:",
      "*Teaching Style:* Is the teaching approach engaging and easy to follow, or does it feel disconnected and difficult to stay focused on?",
      "*Pace:* Is the lesson moving at a comfortable speed, or does it feel too fast or too slow?",
      "*Quality:* Are the explanations, examples, and overall delivery actually helping students learn effectively?",
      "*Simplicity:* Are complex concepts being broken down into simpler ideas that are easier to grasp?",
      "*Understandability:* After the lesson, do students genuinely understand the topic, or are they still confused but afraid to say it?",
      "*Complaints & Observations:* A safe space for honest comments like \"The screen share is blurry,\" \"The AC is freezing,\" or \"Can we please take a short break before our brains melt?\"",
      "The Stack Behind Class Echo",
      "From a development perspective, I wanted Class Echo to feel fast, responsive, and easy to use on any device. The current stack includes: Frontend: React 19, TanStack Start, Tailwind CSS, TypeScript. UI Components: Shadcn/ui, Radix UI, Lucide Icons. Backend: Supabase (PostgreSQL + Auth). Build Tool: Vite with TanStack Router.",
      "Mobile responsiveness was a huge priority because, realistically, most students are going to submit honest feedback from their phones during class. The experience needed to feel quick, smooth, and frictionless. Behind the scenes, feedback is aggregated into a private dashboard for instructors. The goal is to help teachers identify patterns over time — whether pacing is too fast, explanations are unclear, or certain materials are not connecting with students.",
      "Still Building, Still Learning",
      "Class Echo is still a work in progress, but it has already changed the way I think about teaching. Instead of relying on forced \"yes, we understand\" responses, I now have a better way to hear what students actually feel during sessions. My hope is that students will genuinely relate to it and feel comfortable enough to be honest without fear of embarrassment or judgment.",
      "Because sometimes the most valuable thing a student can say is: \"I'm lost.\" And as instructors, we should build environments where saying that feels completely okay.",
      "If you're an educator, bootcamp instructor, mentor, or team lead running technical sessions, try replacing the usual \"Does that make sense?\" with an anonymous feedback system. The truth might sting a little at first, but honest feedback is one of the fastest ways to grow. And honestly, I'm excited to keep building Class Echo into something that truly improves the learning experience for both students and instructors.",
    ],
  },
   {
    slug: "the-ultimate-dev-cheat-code-why-mentorship-is-crucial",
    title: "The Ultimate Dev Cheat Code: Why Mentorship is Crucial for Your Coding Career",
    excerpt: "Mentorship is the ultimate cheat code for developers — it helps you skip mistakes, accelerate your growth, and break through self-imposed limits.",
    date: "2026-05-25",
    readTime: "4 min read",
    category: "Career",
    body: [
      "In the software development world, we place a massive premium on autonomy. We pride ourselves on our ability to stare at a cryptic error message for six hours, dive into obscure documentation, and emerge victorious. We treat struggle like a rite of passage.",
      "But here is a hard truth: Going it alone is the slowest way to grow.",
      "While self-reliance is a great trait, navigating a tech career completely solo is like trying to build a full-stack application without using any open-source libraries — sure, you could write everything from scratch, but why reinvent the wheel? That is exactly what a mentor prevents.",
      "Here is why finding a mentor (or becoming one) is the ultimate cheat code for your development career.",
      "1. Skipping the Scar Tissue: Learning from Their Mistakes",
      "There is a famous saying: 'A prudent person learns from their mistakes, but a wise person learns from the mistakes of others.'",
      "As a developer, your career will be full of forks in the road. Should you specialize in a specific framework or remain a generalist? How do you negotiate a tech salary? How do you handle a toxic team dynamic or navigate a massive git merge disaster on a production server?",
      "You can figure all of this out on your own, but it will cost you time, stress, and potentially money.",
      "The Self-Taught Way: You make the mistake, suffer the consequences, and learn the lesson.",
      "The Mentored Way: Your mentor says, 'I did that five years ago, and it blew up in my face. Do this instead.'",
      "A mentor allows you to download years of situational context and 'scar tissue' without having to bleed for it yourself.",
      "2. The Fast-Forward Button for Your Career Trajectory",
      "It is incredibly easy to get stuck in 'Tutorial Hell' or find yourself plateauing at a job where you are no longer learning. When you are inside the jar, you can't read the label. You don't always know what skills are actually in demand or what gaps exist in your current portfolio.",
      "A mentor acts as a high-level architect for your career. They help you look past the daily grind and focus on the macro trends:",
      "They point out which technologies are actually worth learning and which are just passing hype.",
      "They review your code, your GitHub architecture, and your resume through the eyes of a hiring manager.",
      "They open doors to networks and opportunities that are completely invisible on public job boards.",
      "By helping you focus only on what moves the needle, a mentor effectively hits the fast-forward button on your transition from junior to mid-level, and mid-level to senior.",
      "3. Pushing Past Your Self-Imposed Ceilings",
      "We are naturally wired to seek comfort. Once we get comfortable with a specific tech stack or a certain level of responsibility, we tend to camp out there. Combine that comfort with a healthy dose of Imposter Syndrome, and many brilliant developers end up playing small for years.",
      "A great mentor doesn’t just comfort you; they stretch you. They see potential in you that your imposter syndrome won't let you see yourself.",
      "A good mentor sees your current limits and deliberately pushes you past them. They assign you the complex architecture task, challenge your sloppy optimization choices, and force you out of your comfort zone because they know that's where true engineering capability is forged.",
      "When you have someone credible holding you accountable and saying, 'You are capable of handling this architecture, now go build it,' your self-imposed ceilings vanish.",
      "The Takeaway",
      "Mentorship isn't about finding someone to give you the answers to your homework. It’s about building a relationship with someone who has already walked the path you are currently coding.",
      "If you are a junior or mid-level dev, look for someone whose career looks like your 5-year goal. If you are a senior dev, remember that the best way to solidify your own knowledge is to explain it to someone else. Stop coding your career on pure vibes—find a mentor, absorb the wisdom, and pay it forward.",
    ]},
  {
    slug: "the-art-of-vibe-coding",
    title: "The Art of Vibe Coding: What to Know Before Letting AI Agents Build Your App",
    excerpt: "There is a new phenomenon sweeping through the tech world, and it goes by a glorious name: Vibe Coding. Here is what you need to know before you hand over the keys.",
    date: "2026-05-24",
    readTime: "3 min read",
    category: "Engineering",
    body: [
      "There is a new phenomenon sweeping through the tech world, and it goes by a glorious name: Vibe Coding.",
      "Coined to describe the act of leaning back, sipping your coffee, and typing high-level instructions while an AI agent (like Bolt.new, Devin, or Lovable) spins up a full-stack application, it feels like pure magic. You aren't wrestling with syntax; you are managing intent. You are coding on pure vibes.",
      "But as anyone who has tried to scale a 'vibe-coded' app knows, the hangover can hit hard. Before you hand the keys of your next big project over to an AI agent, here is a breakdown of what you need to know, along with the honest pros and cons.",
      "3 Things to Note Before You Vibe Code",
      "If you go into an AI agent workflow blind, you will likely end up with a tangled web of code that even the AI can't fix. Keep these three rules in mind before you hit enter:",
      "1. The Agent Needs a Director, Not Just a Prompt,\nAI agents are incredibly powerful, but they lack intuition. If you tell an agent to 'build a fintech app,' it will guess the database structure, the authentication flow, and the UI. Defined architecture and scope upfront is essential.",
      "2. Guard Your Context Window\nAs your project grows, the codebase gets heavier. If you let the AI generate bloated, repetitive code, it will quickly hit its context limit. Once that happens, the agent will begin to 'forget' earlier features or introduce bugs into working code.",
      "3. Prompting is the New Refactoring\nIn traditional coding, you rewrite functions to clean them up. In vibe coding, you must rewrite your prompts to guide the AI to clean up its own mess. If the AI introduces a bug, tell it exactly where the logic deviated.",
      "The Pros: Why Vibe Coding Feels Like a Superpower",
      "0 to MVP in Record Time: The speed of prototyping is unparalleled. What used to take a solo developer two weeks of setup can now be accomplished in an afternoon.",
      "Democratization of Product Building: It bridges the gap between ideation and execution. Founders and designers can now build functional prototypes without waiting for a dedicated engineering team.",
      "Bypassing the 'Syntax Wall': You no longer get stuck for hours because of a missing comma or mismatched bracket. The AI handles the plumbing.",
      "The Cons: The Harsh Realities of Agentic Code",
      "The Infinite Agent Loop: This happens when the agent attempts to fix a bug, creates a new bug, and accidentally deletes a feature that worked twenty prompts ago.",
      "Compounding Technical Debt: AI agents often copy-paste code instead of modularizing it, leading to massive, unmaintainable files if not carefully directed.",
      "The 'Black Box' Problem: If you don't actually understand the code the AI is writing, you don't really own the application. You are left with code you cannot debug yourself when the AI hits a wall.",
      "The Golden Rule: Use AI agents to accelerate your velocity, not to replace your critical thinking.",
      "Vibe coding is not a fad; it is the evolutionary next step of software development. It shifts the human developer's role from a bricklayer to an architect. If you are building a prototype, go all in. If you are building mission-critical software, keep your hands on the keyboard and audit every line.",
    ],
  },
  {
    slug: "building-sakosile-challenges-lessons-growth",
    title: "Building SAKOSILE: Challenges, Lessons, and Growth as a Frontend Developer",
    excerpt: "Building SAKOSILE was more than just creating a web application — it was a project that challenged my problem-solving skills and improved my understanding of frontend architecture.",
    date: "2026-05-23",
    readTime: "3 min read",
    category: "Case Study",
    body: [
      "Building SAKOSILE was more than just creating a web application — it was a project that challenged my problem-solving skills, improved my understanding of frontend architecture, and pushed me to think more deeply about user experience and scalability.",
      "One of the biggest challenges I faced during development was implementing routing for multiple user roles. The application required different access levels and experiences depending on the type of user logged in. Managing protected routes, conditional rendering, authentication flow, and ensuring users only accessed the pages relevant to their role became a complex but rewarding part of the project.",
      "I had to carefully structure the routing system to maintain both security and scalability while keeping the codebase organized and maintainable. This experience helped me better understand application architecture and role-based access control in modern frontend development.",
      "Another major focus during the project was responsiveness and adaptability across all screen sizes. I wanted SAKOSILE to provide a seamless experience whether users accessed it from a mobile phone, tablet, laptop, or large desktop screen. Achieving this required a lot of testing, layout restructuring, and attention to spacing, typography, and component behavior on different devices.",
      "From flexible grids to responsive navigation and adaptive UI components, I learned the importance of designing with users in mind rather than only focusing on functionality.",
      "Beyond the technical side, SAKOSILE taught me patience, consistency, and the importance of writing scalable and maintainable code. Every bug fixed and every feature completed contributed to my growth as a frontend developer.",
      "Looking back, the project was not just about building an application — it was about becoming a better developer through real-world challenges and hands-on experience.",
    ],
  },
  {
    slug: "building-kumani-reusable-modules",
    title: "Building KUMANI: How Reusable Modules Improved My Development Process",
    excerpt: "While building KUMANI, one of the biggest lessons I learned was the importance of reusable modules in frontend development.",
    date: "2026-05-22",
    readTime: "2 min read",
    category: "Architecture",
    body: [
      "While building KUMANI, one of the biggest lessons I learned was the importance of reusable modules in frontend development. Instead of rewriting the same logic and UI structure multiple times, I focused on creating reusable components and modules that could be used across different parts of the application.",
      "At the beginning of the project, I noticed that many sections shared similar layouts, buttons, cards, form structures, and functionality. Rather than duplicating code, I started breaking the application into smaller reusable pieces. This made the project more organized, easier to maintain, and faster to scale as new features were added.",
      "Reusable modules also helped improve consistency throughout the application. Since the same components were used across multiple pages, the UI remained uniform and easier for users to navigate. It also reduced bugs because changes made in one component automatically reflected everywhere the module was used.",
      "Another advantage was development speed. As the project grew, having reusable modules allowed me to build new pages and features much faster without starting from scratch every time. It also made debugging easier because the logic was centralized instead of scattered across different files.",
      "This experience taught me that writing reusable and scalable code is just as important as building functional features. KUMANI helped me better understand component architecture, maintainability, and the long-term benefits of modular frontend development.",
    ],
  },
  {
    slug: "shipping-react-faster",
    title: "Shipping React Faster Without Burning the Codebase",
    excerpt:
      "Lessons from rebuilding internal tooling at Harley Innovations: how component primitives, SSR and pragmatic caching cut iteration time in half.",
    date: "2026-05-21",
    readTime: "2 min read",
    category: "Engineering",
    body: [
      "When I joined the team, every new screen felt like starting from scratch. Buttons drifted, spacing wandered, and TypeScript errors lived in a folder no one opened.",
      "We did three things, in this order: extracted a small set of primitives, locked the design tokens, and moved data fetching to the server. Nothing fancy — but together they removed entire categories of bugs.",
      "Primitives first. We picked 12 components — Button, Input, Field, Card, Sheet, Dialog, Tabs, Avatar, Badge, Menu, Tooltip, Toast — and forbade ad-hoc variants in feature code. Every variant must be added to the primitive.",
      "Then tokens. Color, radius, spacing and font tokens went into one CSS file. Feature code only consumes semantic tokens (bg-card, text-muted-foreground), never raw values. That alone killed half our drift.",
      "SSR with TanStack Start gave us per-route loaders and tiny client bundles. Most pages render before JS finishes — and the few interactive bits hydrate where needed.",
      "Six weeks later, ticket throughput nearly doubled. Not because we worked harder — because the codebase stopped pushing back.",
    ],
  },
  {
    slug: "ssr-tradeoffs",
    title: "The SSR Tradeoffs Nobody Warns You About",
    excerpt:
      "SSR is great for SEO and first paint — but it changes how you think about state, auth, and analytics. Here's what I learned the slow way.",
    date: "2026-05-20",
    readTime: "1 min read",
    category: "Architecture",
    body: [
      "SSR isn't a free upgrade. It's a different runtime model — and if you treat it like a sticker you add to a Vite app, you'll hit subtle issues for weeks.",
      "Issue one: window. Anything that touches window, localStorage or document at module scope crashes on the server. Move it inside useEffect or wrap with a typeof guard.",
      "Issue two: auth. Your session cookie is on the request, not in localStorage. Loaders must read from the request context — not call a client SDK.",
      "Issue three: analytics. Page views fire on the client after hydration. Don't double-count by also firing in a server loader.",
      "Done right, SSR pays off. Done blindly, it doubles your error budget. Go in with eyes open.",
    ],
  },
  {
    slug: "design-systems-for-small-teams",
    title: "Design Systems For Small Teams (Without the Overhead)",
    excerpt:
      "You don't need a 200-component library. You need 12 components, 6 tokens, and a rule everyone respects.",
    date: "2026-05-19",
    readTime: "2 min read",
    category: "Design",
    body: [
      "The phrase 'design system' has scared a lot of small teams into doing nothing. They think it means a year-long project, a Figma library and a Storybook deploy.",
      "It doesn't. A useful system for a 3-person team is a CSS file with semantic tokens, a handful of styled primitives, and one rule: no raw hex in feature code.",
      "Start with color, spacing and radius tokens. Add a Button. Add an Input. When the third Card appears, extract it. Grow the system from real pain, not speculation.",
      "The point isn't completeness — it's consistency. Twelve components used everywhere beats two hundred used sometimes.",
    ],
  },
];

export function getPost(slug: string) {
  return posts.find((p) => p.slug === slug);
}
