import Image from "@/assets/404_not_found_dev_meme.svg";
import classEcho from "@/assets/class-echo.png";
import sakosile from "@/assets/sakosile.png";
import tanstackImage from "@/assets/tanstack.webp";
import devAiCollab from "@/assets/developer_ai_collaboration_cover.svg";
import devSplitContrast from "@/assets/developer_split_contrast_cover.svg";

export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  readTime: string;
  category: string;
  heroImage?: string;
  body: string[];
};


export const posts: Post[] = [
  {
    slug: "concept-to-code-dennic-electrical",
    title: "From Concept to Code: Building the Dennic Electrical Website",
    excerpt: "A look into how I built a modern, responsive, and interactive website for Dennic Electrical Construction Company.",
    date: "2026-07-07",
    readTime: "4 min read",
    category: "Engineering",
    body: [
      "As a frontend developer, one of the most satisfying experiences is taking a client's vision and turning it into a polished, high-performing digital reality. Recently, I had the pleasure of building the website for **Dennic Electrical Construction Company**, a project that challenged me to balance corporate professionalism with modern web aesthetics.",
      "In this post, I want to walk you through my journey from the initial concept to the final, deployed code.",
      "## Understanding the Concept and Client Needs",
      "Dennic Electrical isn't just any company; they deal with heavy-duty construction and electrical engineering. Their website needed to exude trust, reliability, and precision. During the initial discovery phase, a few core requirements stood out:",
      "- **Professional & Authoritative:** The color palette and typography needed to feel grounded. We landed on a strong \"Navy Deep\" primary color.",
      "- **Showcase of Work:** A dedicated Projects section was essential to display their past construction and electrical jobs.",
      "- **Responsive & Accessible:** Clients might be viewing the site from a desktop in an office or a mobile phone on a construction site. It had to work flawlessly everywhere.",
      "## Choosing the Tech Stack",
      "To ensure the site was blazingly fast and easy to maintain, I went with my trusted modern stack:",
      "- **React (via Vite):** For a snappy, component-driven architecture.",
      "- **Tailwind CSS:** For rapid, highly-customizable styling without leaving the markup.",
      "- **TypeScript:** To catch errors early and ensure the data structures (like project lists and services) were strongly typed.",
      "## Designing the Architecture",
      "A corporate website like this benefits from a clean, predictable structure. I broke the site down into clear, distinct routes: `/`, `/about`, `/services`, and `/projects`.",
      "Each of these pages was wrapped in a consistent layout. For example, maintaining the global theme was as simple as wrapping the main content in a container styled with Tailwind with responsive padding (`pt-24 sm:pt-28 md:pt-32`) to ensure the content always sits perfectly below the fixed header, regardless of whether the user is on a tiny mobile screen or a massive ultrawide monitor.",
      "## Overcoming Challenges: The Navigation",
      "One of the interesting challenges was the navigation. Corporate sites need clear routing, but they also need to look modern. I implemented a solid header for desktop users, but for mobile, I built a custom slide-out `Sidebar` component.",
      "This required careful state management to ensure smooth transitions and accessibility (making sure focus is trapped within the sidebar when it's open, and that it can be closed with the escape key).",
      "## Pushing Boundaries: Interactive 3D Elements",
      "To truly make the site stand out and feel premium, I integrated an interactive 3D element. Instead of flat, static images for their core engineering concepts, I brought in a dynamic 3D model that users can interact with. This wasn't just for show—it demonstrated Dennic's commitment to cutting-edge technology and precision engineering. Balancing the 3D performance with the site's overall speed was a fun challenge, requiring careful lazy loading and canvas optimization.",
      "## Highlighting the Services and Projects",
      "The bread and butter of the Dennic website are the **Services** and **Projects** pages.",
      "Instead of just dumping text on a page, I built reusable card components. These components accept props for the title, description, and an image or icon. This modular approach meant that if the client wants to add a new service next month, it's just a matter of adding a new object to a data array—no layout changes required.",
      "## Conclusion",
      "Building the Dennic Electrical website was a fantastic exercise in translating a rugged, real-world industry into a sleek, professional web presence. It reinforced my belief that the right tech stack combined with a clear understanding of the client's goals always leads to a successful launch."
    ]
  },
  {
    slug: "ai-isnt-taking-your-job-the-developer-who-uses-it-well-is",
    title: "AI Isn't Taking Your Job. The Developer Who Uses It Well Is.",
    excerpt: "The real shift isn't AI vs. developers — it's developers who've integrated AI into their workflow vs. developers who haven't.",
    heroImage: devAiCollab,
    date: "2026-06-24",
    readTime: "4 min read",
    category: "Engineering",
    body: [
      "There's a version of this conversation that's mostly noise — doom threads about AI replacing programmers within five years, hot takes from people who've never shipped a feature with Copilot open. I want to skip past that and talk about what's actually happening on the ground, because it's more specific, and more useful, than \"AI is coming for us.\"",
      "## The real shift isn't AI vs. developers",
      "It's developers who've integrated AI into their workflow vs. developers who haven't.",
      "That's the whole story. Not man vs. machine — it's two different developers applying for the same role, one of them shipping noticeably faster, and a hiring manager or client noticing the gap.",
      "I've felt this shift directly. Debugging a TanStack Router SSR mismatch used to mean hours of manually tracing render output between server and client. Now I can describe the symptom, get a shortlist of likely causes ranked by probability, and verify the right one in minutes instead of hours. The debugging instinct still has to be mine — knowing *which* suggestion actually fits my route structure took experience, not a prompt. But the search space narrowed dramatically.",
      "That's the pattern worth paying attention to: AI doesn't replace the judgment. It compresses the time between \"something's wrong\" and \"I understand why.\"",
      "## What AI is actually good at (and bad at)",
      "To use these tools well, you need an honest read on their limits.",
      "**Strong at:** boilerplate, syntax recall across languages you don't touch daily, first-draft test cases, explaining unfamiliar error messages, summarizing documentation, refactoring suggestions once you've defined the target shape.",
      "**Weak at:** understanding the actual constraints of your system — your specific hosting setup, your team's conventions, the business reason a feature has to work a certain way. It will confidently suggest a fix that's syntactically perfect and contextually wrong, and it won't flag that for you. You have to.",
      "This is exactly why the developers who benefit most aren't the ones blindly accepting suggestions. They're the ones who already understand the problem well enough to evaluate the output critically — and use AI to move faster through the parts they've already mentally solved.",
      "## The skill that's actually becoming valuable",
      "Prompting well is a small part of this. The bigger skill is the same one that's always mattered: knowing what question to ask.",
      "If you don't understand why an SSR mismatch happens, no amount of AI assistance will help you debug one efficiently — you'll paste error messages without context and get generic answers back. If you do understand it, you can describe the actual symptom precisely, and the tool becomes genuinely fast.",
      "In other words: AI raises the ceiling for developers who already have strong fundamentals, and it's far less useful — sometimes actively misleading — for developers who don't.",
      "That's the uncomfortable part of this conversation that doesn't get said enough. The tools aren't a substitute for understanding your stack. They're a force multiplier on understanding you already have.",
      "## What this means practically",
      "If you're early in your career, this isn't a reason to panic — it's a reason to be deliberate. Use AI tools while you're learning, but don't let them replace the parts of learning that build judgment: reading error messages slowly, understanding why a fix works and not just that it works, building your own mental model of how your framework behaves under the hood.",
      "If you're further along, the move is integration, not resistance. The developers I see moving fastest right now aren't the ones who've memorized more syntax. They're the ones who've figured out where AI shortens their loop — code review prep, test scaffolding, documentation, first-pass debugging — and where it doesn't, and they haven't blurred that line.",
      `![Developer AI Collaboration](${devSplitContrast})`,
      "AI isn't going to write your portfolio, decide your project architecture, or know that your client actually needs fee management bundled with result publishing instead of two separate products. That judgment is still yours. The job isn't disappearing. It's shifting toward the developers willing to treat AI as infrastructure rather than either a threat or a crutch.",
      "That shift is already happening. The only real question is which side of it you're building your skills for.",
      "---",
      "*Currently building Gradifyre, a school management platform for Nigerian schools — and yes, AI tools are part of how it gets built.*"
    ]
  },
  {
    slug: "the-week-git-lfs-tanstack-router-and-deployment-teamed-up",
    title: "The Week Git LFS, TanStack Router, and Deployment Teamed Up Against Me",
    excerpt: "A real account of an SSR mismatch, a file-size limit, and how I ended up rebuilding in Next.js.",
    heroImage: tanstackImage,
    date: "2026-06-24",
    readTime: "4 min read",
    category: "Deployment",
    body: [
      "Every developer has a project that humbles them. This was mine.",
      "It started normally enough: code committed, assets tracked, TanStack Router handling navigation the way it's supposed to. I pushed, set up the deploy, and figured I'd have this live within the hour.",
      "That was not how the day went.",
      "---",
      "## Chapter one: Git LFS and the file-size limit nobody warns you about",
      "Git LFS (Large File Storage) works beautifully on your local machine. You track your large files — images, media, whatever heavy assets your project needs — and everything commits and pushes without complaint.",
      "The problem shows up at deploy time.",
      "Most hosting providers cap LFS bandwidth and storage on free or standard tiers, and that cap is rarely visible until you exceed it. There's no warning beforehand. The build simply fails, often with an error message vague enough that you start second-guessing your own setup before you even get to the real cause.",
      "In my case, it was a straightforward `file size limit exceeded` — four words that cost me a full Saturday of debugging before I traced it back to LFS quotas rather than anything in my actual code.",
      "---",
      "## Chapter two: the SSR mismatch with TanStack Router",
      "To be clear upfront: TanStack Router is a solid library. This isn't a takedown of the ecosystem — it's an account of how one specific mismatch nearly broke my patience.",
      "An SSR (server-side rendering) mismatch happens when the server renders one version of a page and the client renders a different version of that same page on hydration. React compares the two and, when they don't line up, throws hydration warnings — sometimes cascading into broken UI, sometimes just noisy console errors that mask the real issue underneath.",
      "What made this particularly frustrating was the way it compounded. I'd fix one mismatch — usually traced to a loader returning slightly different data shapes server-side vs. client-side — and a new one would surface somewhere else in the route tree. Each fix exposed another layer. I went through my route definitions, loaders, and component structure more than once trying to isolate exactly where client and server state were diverging.",
      "By the end of it, I knew that loading spinner a little too well.",
      "---",
      "## Chapter three: deployment, where both problems collided",
      "By the time I reached deployment, I'd already fixed the SSR issues and thought I was clear. I wasn't.",
      "`Build failed.`",
      "I checked environment variables — fine. I checked routes — fine, as far as I could tell. Then I checked the LFS files again, because they were still quietly consuming bandwidth in the background, unrelated to anything I'd just fixed in the router. Two separate problems, same deploy pipeline, each one masking the other's error output.",
      "I pushed again. Failed again. At that point it stopped being a single bug to fix and became a process of isolating which failure belonged to which system — LFS quota issues showing up as generic build failures, SSR mismatches showing up as runtime hydration warnings that only appeared in production, not locally.",
      "---",
      "## Why I moved to Next.js",
      "This wasn't a decision I made mid-crisis. It came after, once I'd actually fixed both issues and had time to weigh whether I wanted to keep solving this category of problem on every project going forward.",
      "To be specific about what changed:",
      "- **File-based routing** removed an entire class of configuration I'd been managing manually with TanStack Router.",
      "- **Built-in SSR handling** in Next.js meant the client/server data shape mismatches I'd spent days chasing simply weren't something I had to architect myself — the framework's data-fetching patterns (`getServerSideProps` / App Router server components) are designed around avoiding that exact hydration gap.",
      "- It didn't eliminate the LFS issue — that's a Git/hosting-level problem independent of framework — but it did mean I was no longer debugging two unrelated failure modes inside the same build pipeline.",
      `![TanStack Router vs Next.js](${tanstackImage})`,
      "I've deployed three projects since the switch without a single hydration warning. I'm not claiming Next.js is objectively superior to TanStack Router for every use case — but for how I build and where I deploy, it removed a category of friction that TanStack Router's flexibility was costing me.",
      "---",
      "## What I'd tell another developer hitting this",
      "1. **Check your hosting provider's Git LFS bandwidth and storage limits before you commit large files across your history.** The failure shows up at deploy time, not commit time, which makes it harder to trace.",
      "2. **Treat every hydration warning as worth investigating immediately**, even if the page still renders. They tend to compound rather than resolve on their own.",
      "3. **Isolate failures by system before assuming they're related.** I lost time treating the LFS quota issue and the SSR mismatch as one problem when they were two separate failures sharing a build pipeline.",
      "4. **A framework switch is a legitimate engineering decision, not a failure.** Choosing Next.js over a more manual TanStack Router setup, for my workflow, removed recurring friction rather than just working around a one-off bug.",
      "If you're dealing with TanStack Router SSR mismatches or LFS-related deploy failures right now, I hope this saves you some of the time it cost me to trace both issues back to their root causes.",
      "---",
      "*Working through a similar setup or have a different take on TanStack Router's SSR model? I'd be glad to hear about it — reach out via the contact page.*"
    ]
  },
  {
    slug: "responsive-design-isnt-about-mobile-its-about-uncertainty",
    title: "Responsive Design Isn't About Mobile. It's About Uncertainty.",
    excerpt: "The biggest lesson I learned is that responsive design is not about adapting to different screen sizes. It's about adapting to uncertainty.",
    date: "2026-06-10",
    readTime: "3 min read",
    category: "Design",
    body: [
      "Most frontend developers think responsive design starts when the screen gets smaller. That's usually where the problems begin.",
      "Early in my career, my approach to responsiveness was simple: build the desktop version first, add a few media queries, test on my phone, and call it done. The design looked great until real users started interacting with it.",
      "Someone increased their browser zoom to 125%. A product name became twice as long as expected. A table suddenly contained hundreds of rows. A client uploaded a profile picture with strange dimensions. And just like that, the \"responsive\" interface wasn't responsive anymore.",
      "The biggest lesson I learned is that responsive design is not about adapting to different screen sizes. It's about adapting to uncertainty.",
      "Stop Designing for the Screenshot",
      "Many developers build interfaces around the design file they received. The problem is that users don't interact with screenshots. They interact with data.",
      "That perfectly aligned card in Figma might contain: A two-word title today, a twelve-word title tomorrow, or no title at all next week. If your layout breaks because the content changed, then the design was never truly responsive.",
      "Instead of asking: \"How does this look on mobile?\" Start asking: \"What happens when the content behaves differently than I expected?\" That single question will improve your UI more than dozens of media queries.",
      "Let Content Drive the Layout",
      "One mistake I see often is forcing content into rigid containers. A better approach is to allow layouts to adapt naturally.",
      "For example, when building card grids, avoid deciding that there must always be three cards per row. Instead, define the minimum space a card needs and allow the layout engine to decide how many fit.",
      "When content becomes the source of truth, your interface becomes far more resilient.",
      "Test With Bad Data",
      "Most developers test with ideal data. Real users rarely provide ideal data.",
      "When building a component, deliberately test it with: Extremely long names, empty fields, broken images, large numbers, and unexpected text lengths. I call this \"designing for chaos.\"",
      "If a component survives bad data, it will survive production.",
      "Think Beyond Width",
      "Responsiveness is often treated as a width problem. In reality, there are many dimensions to responsiveness: Screen width, screen height, zoom levels, font scaling, language expansion, accessibility settings, and dynamic content.",
      "A layout that works perfectly at 1440px can still fail when a user increases text size. Great interfaces respond to all of these variables, not just viewport width.",
      "Every Component Should Be Independent",
      "One habit that transformed the way I build UIs is treating every component as if it will eventually be reused somewhere unexpected. Because it probably will.",
      "That dashboard card you built today may end up inside a sidebar tomorrow. That modal content may become a standalone page next month.",
      "When components are flexible and self-contained, responsiveness becomes much easier to maintain as projects grow.",
      "Responsive Design Is a Mindset",
      "The best responsive developers aren't the ones who know the most CSS tricks. They're the ones who assume things will change. Because they always do.",
      "Users change. Content changes. Requirements change. Screen sizes change.",
      "The goal isn't to predict every scenario. The goal is to build interfaces that remain useful when those scenarios arrive.",
      "And that's what true responsiveness really is. Not adapting to screens. Adapting to change."
    ]
  },
  {
    slug: "beyond-deploy-button-spa-vs-ssr",
    title: "Beyond the \"Deploy\" Button: How Hosting Platforms Actually See Your SPA vs. SSR Apps",
    excerpt: "Why SPAs can 404 on refresh and SSR apps can surprise you with cold starts, what hosting platforms actually do after you click Deploy.",
    heroImage: Image,
    date: "2026-06-04",
    readTime: "6 min read",
    category: "Deployment",
    body: [
      "We’ve all been there. You run `npm run build`, push to GitHub, connect to Vercel (or Netlify), and celebrate the glorious ‘Deployment Successful’ checkmark. Then you refresh a sub-page and 404. Or you deploy an SSR app and wonder why your first-byte time or cloud bill just spiked.",
      "Understanding how hosting platforms treat Single Page Applications (SPAs) versus Server-Side Rendered (SSR) apps after the build step saves hours of debugging. Here’s a practical breakdown.",
      "---",
      "## 1. The Single Page Application (SPA)",
      "**Featuring:** React (Vite), Vue, Vanilla JS",
      "### How the hosting platform sees it: “You're just a box of rocks”",
      "To the host, your SPA is a folder of static assets: one `index.html`, some compiled `.js` and `.css` files, and images. The platform typically deploys those files to a CDN (Content Delivery Network), which serves the files from servers near users.",
      "### The frontend gotcha: client-side routing and the dreaded 404",
      "When a user navigates inside your app, the client-side router updates the URL and renders new views. But if the user refreshes `yoursite.com/dashboard`, the browser requests `/dashboard` from the server. The CDN looks for a `/dashboard` file, finds none, and returns 404.",
      "### How to fix it",
      "Tell the host to serve `index.html` for every route so the client app can handle routing. Examples: add a `vercel.json` or a `_redirects` file for Netlify, or configure CloudFront/S3 to rewrite 404s to `index.html` with a 200 status.",
      "---",
      "## 2. The Server-Side Rendered (SSR) App",
      "**Featuring:** Next.js, Nuxt, Remix",
      "### How the hosting platform sees it: “You are a living, breathing organism”",
      "An SSR build produces server code not just static files. The platform must run server processes (Node servers or serverless functions) that render HTML on each request, fetching data and composing pages at runtime.",
      "### How platforms handle SSR (serverless and edge functions)",
      "Modern hosts slice SSR apps into serverless or edge functions. When a request arrives, the platform spins up a function to render the page, then tears it down when done — efficient, but with tradeoffs.",
      "### The frontend gotchas",
      "- **Cold starts:** Functions that haven’t run recently can add 1–2s latency on the first request.\n- **Environment variables:** With SSR, secrets and runtime config must be set in the host dashboard (not baked into client JS).\n- **Region latency:** If your DB is in `us-east-1` but the function runs in another region, data fetches add latency.",
      "---",
      // (removed SPA vs. SSR table per request)
      "---",
      "## The Frontend Takeaway",
      "Don’t pick SSR because it’s trendy, and don’t pick SPA just because it’s easy. Choose based on product needs: if SEO and fast initial paint matter (blogs, marketing sites, public dashboards), accept server complexity and use SSR on a platform optimized for it. If you’re building an authenticated SaaS where users live inside the app, deploy as an SPA to a CDN and save yourself compute costs.",
      "Happy deploying! 🚀",
      "---",
      "**Notes & practical fixes**",
      "- SPA rewrite examples: use `_redirects` on Netlify (`/* /index.html 200`) or `vercel.json` with a fallback.\n- SSR tips: provision environment variables in your host settings and colocate your database and functions to reduce latency.",
      "What’s your go-to hosting setup? Ever been burned by an SSR bill or an SPA 404? Let’s talk in the comments.",
    ],
  },
  {
    slug: "yes-i-understand-lie-class-echo",
    title: "The \"Yes, I Understand\" Lie: Why I Started Building Class Echo to Save My Teaching Sanity",
    excerpt: "Most students pretend they understand to avoid embarrassment. I built Class Echo to create a safe space for honest feedback without the performance anxiety.",
    heroImage: classEcho,
    date: "2026-05-29",
    readTime: "5 min read",
    category: "Education",
    body: [
      "Picture this: you're standing in front of a classroom, pouring your heart and soul into explaining a complex tech concept something like asynchronous data fetching or nested React state management.",
      "You pause, take a sip of water, look around the room, and ask the ultimate forbidden question:",
      "\"Does everyone understand so far?\"",
      "Right on cue, the entire class gives you synchronized nods. \"Yes, instructor.\" \"We understand.\" \"Everything is fine.\"",
      "Spoiler alert: they absolutely did not understand. In reality, most of them were completely lost.",
      "As a facilitator at Harley Innovations Hub, I ran into this problem very early. I could see the confusion on some faces, but publicly, the response was always positive. That's when I realized something important about classroom psychology: Students will often pretend they understand just to avoid being the only person admitting they are confused. Nobody wants to raise their hand at 4:30 PM and say, \"I have no idea what's going on.\"",
      "The problem is, without an honest and safe feedback system, teaching starts to feel like operating in the dark. You can't improve a lesson if you don't know where students are struggling. So, being a frontend engineer, I did what any developer would do when faced with a communication problem: I opened VS Code and started building a solution. I call it Class Echo.",
      "Moving From Vague Nods to Real Feedback",
      "The philosophy behind Class Echo is simple: remove friction. I didn't want to create another bloated learning management system with long signup processes and unnecessary complexity. If students need to create an account just to say \"the class is moving too fast,\" most of them simply won't bother.",
      "Instead, Class Echo allows instructors to generate a quick link where students can anonymously submit feedback in real time. To make the feedback actually useful, I avoided generic questions like \"How was class today?\" and focused on six specific areas instead:",
      "*Teaching Style:* Is the teaching approach engaging and easy to follow, or does it feel disconnected and difficult to stay focused on?",
      "*Pace:* Is the lesson moving at a comfortable speed, or does it feel too fast or too slow?",
      "*Quality:* Are the explanations, examples, and overall delivery actually helping students learn effectively?",
      "*Simplicity:* Are complex concepts being broken down into simpler ideas that are easier to grasp?",
      "*Understandability:* After the lesson, do students genuinely understand the topic, or are they still confused but afraid to say it?",
      "*Complaints & Observations:* A safe space for honest comments like \"The screen share is blurry,\" \"The AC is freezing,\" or \"Can we please take a short break before our brains melt?\"",
      "The Stack Behind Class Echo",
      "From a development perspective, I wanted Class Echo to feel fast, responsive, and easy to use on any device. The current stack includes: Frontend: React 19, TanStack Start, Tailwind CSS, TypeScript. UI Components: Shadcn/ui, Radix UI, Lucide Icons. Backend: Supabase (PostgreSQL + Auth). Build Tool: Vite with TanStack Router.",
      "Mobile responsiveness was a huge priority because, realistically, most students are going to submit honest feedback from their phones during class. The experience needed to feel quick, smooth, and frictionless. Behind the scenes, feedback is aggregated into a private dashboard for instructors. The goal is to help teachers identify patterns over time — whether pacing is too fast, explanations are unclear, or certain materials are not connecting with students.",
      "Still Building, Still Learning",
      "Class Echo is still a work in progress, but it has already changed the way I think about teaching. Instead of relying on forced \"yes, we understand\" responses, I now have a better way to hear what students actually feel during sessions. My hope is that students will genuinely relate to it and feel comfortable enough to be honest without fear of embarrassment or judgment.",
      "Because sometimes the most valuable thing a student can say is: \"I'm lost.\" And as instructors, we should build environments where saying that feels completely okay.",
      "If you're an educator, bootcamp instructor, mentor, or team lead running technical sessions, try replacing the usual \"Does that make sense?\" with an anonymous feedback system. The truth might sting a little at first, but honest feedback is one of the fastest ways to grow. And honestly, I'm excited to keep building Class Echo into something that truly improves the learning experience for both students and instructors.",
    ],
  },
   {
    slug: "the-ultimate-dev-cheat-code-why-mentorship-is-crucial",
    title: "The Ultimate Dev Cheat Code: Why Mentorship is Crucial for Your Coding Career",
    excerpt: "Mentorship is the ultimate cheat code for developers — it helps you skip mistakes, accelerate your growth, and break through self-imposed limits.",
    date: "2026-05-25",
    readTime: "4 min read",
    category: "Career",
    body: [
      "In the software development world, we place a massive premium on autonomy. We pride ourselves on our ability to stare at a cryptic error message for six hours, dive into obscure documentation, and emerge victorious. We treat struggle like a rite of passage.",
      "But here is a hard truth: Going it alone is the slowest way to grow.",
      "While self-reliance is a great trait, navigating a tech career completely solo is like trying to build a full-stack application without using any open-source libraries — sure, you could write everything from scratch, but why reinvent the wheel? That is exactly what a mentor prevents.",
      "Here is why finding a mentor (or becoming one) is the ultimate cheat code for your development career.",
      "1. Skipping the Scar Tissue: Learning from Their Mistakes",
      "There is a famous saying: 'A prudent person learns from their mistakes, but a wise person learns from the mistakes of others.'",
      "As a developer, your career will be full of forks in the road. Should you specialize in a specific framework or remain a generalist? How do you negotiate a tech salary? How do you handle a toxic team dynamic or navigate a massive git merge disaster on a production server?",
      "You can figure all of this out on your own, but it will cost you time, stress, and potentially money.",
      "The Self-Taught Way: You make the mistake, suffer the consequences, and learn the lesson.",
      "The Mentored Way: Your mentor says, 'I did that five years ago, and it blew up in my face. Do this instead.'",
      "A mentor allows you to download years of situational context and 'scar tissue' without having to bleed for it yourself.",
      "2. The Fast-Forward Button for Your Career Trajectory",
      "It is incredibly easy to get stuck in 'Tutorial Hell' or find yourself plateauing at a job where you are no longer learning. When you are inside the jar, you can't read the label. You don't always know what skills are actually in demand or what gaps exist in your current portfolio.",
      "A mentor acts as a high-level architect for your career. They help you look past the daily grind and focus on the macro trends:",
      "They point out which technologies are actually worth learning and which are just passing hype.",
      "They review your code, your GitHub architecture, and your resume through the eyes of a hiring manager.",
      "They open doors to networks and opportunities that are completely invisible on public job boards.",
      "By helping you focus only on what moves the needle, a mentor effectively hits the fast-forward button on your transition from junior to mid-level, and mid-level to senior.",
      "3. Pushing Past Your Self-Imposed Ceilings",
      "We are naturally wired to seek comfort. Once we get comfortable with a specific tech stack or a certain level of responsibility, we tend to camp out there. Combine that comfort with a healthy dose of Imposter Syndrome, and many brilliant developers end up playing small for years.",
      "A great mentor doesn’t just comfort you; they stretch you. They see potential in you that your imposter syndrome won't let you see yourself.",
      "A good mentor sees your current limits and deliberately pushes you past them. They assign you the complex architecture task, challenge your sloppy optimization choices, and force you out of your comfort zone because they know that's where true engineering capability is forged.",
      "When you have someone credible holding you accountable and saying, 'You are capable of handling this architecture, now go build it,' your self-imposed ceilings vanish.",
      "The Takeaway",
      "Mentorship isn't about finding someone to give you the answers to your homework. It’s about building a relationship with someone who has already walked the path you are currently coding.",
      "If you are a junior or mid-level dev, look for someone whose career looks like your 5-year goal. If you are a senior dev, remember that the best way to solidify your own knowledge is to explain it to someone else. Stop coding your career on pure vibes—find a mentor, absorb the wisdom, and pay it forward.",
    ]},
  {
    slug: "the-art-of-vibe-coding",
    title: "The Art of Vibe Coding: What to Know Before Letting AI Agents Build Your App",
    excerpt: "There is a new phenomenon sweeping through the tech world, and it goes by a glorious name: Vibe Coding. Here is what you need to know before you hand over the keys.",
    date: "2026-05-24",
    readTime: "3 min read",
    category: "Engineering",
    body: [
      "There is a new phenomenon sweeping through the tech world, and it goes by a glorious name: Vibe Coding.",
      "Coined to describe the act of leaning back, sipping your coffee, and typing high-level instructions while an AI agent (like Bolt.new, Devin, or Lovable) spins up a full-stack application, it feels like pure magic. You aren't wrestling with syntax; you are managing intent. You are coding on pure vibes.",
      "But as anyone who has tried to scale a 'vibe-coded' app knows, the hangover can hit hard. Before you hand the keys of your next big project over to an AI agent, here is a breakdown of what you need to know, along with the honest pros and cons.",
      "3 Things to Note Before You Vibe Code",
      "If you go into an AI agent workflow blind, you will likely end up with a tangled web of code that even the AI can't fix. Keep these three rules in mind before you hit enter:",
      "1. The Agent Needs a Director, Not Just a Prompt,\nAI agents are incredibly powerful, but they lack intuition. If you tell an agent to 'build a fintech app,' it will guess the database structure, the authentication flow, and the UI. Defined architecture and scope upfront is essential.",
      "2. Guard Your Context Window\nAs your project grows, the codebase gets heavier. If you let the AI generate bloated, repetitive code, it will quickly hit its context limit. Once that happens, the agent will begin to 'forget' earlier features or introduce bugs into working code.",
      "3. Prompting is the New Refactoring\nIn traditional coding, you rewrite functions to clean them up. In vibe coding, you must rewrite your prompts to guide the AI to clean up its own mess. If the AI introduces a bug, tell it exactly where the logic deviated.",
      "The Pros: Why Vibe Coding Feels Like a Superpower",
      "0 to MVP in Record Time: The speed of prototyping is unparalleled. What used to take a solo developer two weeks of setup can now be accomplished in an afternoon.",
      "Democratization of Product Building: It bridges the gap between ideation and execution. Founders and designers can now build functional prototypes without waiting for a dedicated engineering team.",
      "Bypassing the 'Syntax Wall': You no longer get stuck for hours because of a missing comma or mismatched bracket. The AI handles the plumbing.",
      "The Cons: The Harsh Realities of Agentic Code",
      "The Infinite Agent Loop: This happens when the agent attempts to fix a bug, creates a new bug, and accidentally deletes a feature that worked twenty prompts ago.",
      "Compounding Technical Debt: AI agents often copy-paste code instead of modularizing it, leading to massive, unmaintainable files if not carefully directed.",
      "The 'Black Box' Problem: If you don't actually understand the code the AI is writing, you don't really own the application. You are left with code you cannot debug yourself when the AI hits a wall.",
      "The Golden Rule: Use AI agents to accelerate your velocity, not to replace your critical thinking.",
      "Vibe coding is not a fad; it is the evolutionary next step of software development. It shifts the human developer's role from a bricklayer to an architect. If you are building a prototype, go all in. If you are building mission-critical software, keep your hands on the keyboard and audit every line.",
    ],
  },
  {
    slug: "building-sakosile-challenges-lessons-growth",
    title: "Building SAKOSILE: Challenges, Lessons, and Growth as a Frontend Developer",
    excerpt: "Building SAKOSILE was more than just creating a web application — it was a project that challenged my problem-solving skills and improved my understanding of frontend architecture.",
    heroImage: sakosile,
    date: "2026-05-23",
    readTime: "3 min read",
    category: "Case Study",
    body: [
      "Building SAKOSILE was more than just creating a web application — it was a project that challenged my problem-solving skills, improved my understanding of frontend architecture, and pushed me to think more deeply about user experience and scalability.",
      "One of the biggest challenges I faced during development was implementing routing for multiple user roles. The application required different access levels and experiences depending on the type of user logged in. Managing protected routes, conditional rendering, authentication flow, and ensuring users only accessed the pages relevant to their role became a complex but rewarding part of the project.",
      "I had to carefully structure the routing system to maintain both security and scalability while keeping the codebase organized and maintainable. This experience helped me better understand application architecture and role-based access control in modern frontend development.",
      "Another major focus during the project was responsiveness and adaptability across all screen sizes. I wanted SAKOSILE to provide a seamless experience whether users accessed it from a mobile phone, tablet, laptop, or large desktop screen. Achieving this required a lot of testing, layout restructuring, and attention to spacing, typography, and component behavior on different devices.",
      "From flexible grids to responsive navigation and adaptive UI components, I learned the importance of designing with users in mind rather than only focusing on functionality.",
      "Beyond the technical side, SAKOSILE taught me patience, consistency, and the importance of writing scalable and maintainable code. Every bug fixed and every feature completed contributed to my growth as a frontend developer.",
      "Looking back, the project was not just about building an application — it was about becoming a better developer through real-world challenges and hands-on experience.",
    ],
  },
  {
    slug: "building-kumani-reusable-modules",
    title: "Building KUMANI: How Reusable Modules Improved My Development Process",
    excerpt: "While building KUMANI, one of the biggest lessons I learned was the importance of reusable modules in frontend development.",
    date: "2026-05-22",
    readTime: "2 min read",
    category: "Architecture",
    body: [
      "While building KUMANI, one of the biggest lessons I learned was the importance of reusable modules in frontend development. Instead of rewriting the same logic and UI structure multiple times, I focused on creating reusable components and modules that could be used across different parts of the application.",
      "At the beginning of the project, I noticed that many sections shared similar layouts, buttons, cards, form structures, and functionality. Rather than duplicating code, I started breaking the application into smaller reusable pieces. This made the project more organized, easier to maintain, and faster to scale as new features were added.",
      "Reusable modules also helped improve consistency throughout the application. Since the same components were used across multiple pages, the UI remained uniform and easier for users to navigate. It also reduced bugs because changes made in one component automatically reflected everywhere the module was used.",
      "Another advantage was development speed. As the project grew, having reusable modules allowed me to build new pages and features much faster without starting from scratch every time. It also made debugging easier because the logic was centralized instead of scattered across different files.",
      "This experience taught me that writing reusable and scalable code is just as important as building functional features. KUMANI helped me better understand component architecture, maintainability, and the long-term benefits of modular frontend development.",
    ],
  },
  {
    slug: "shipping-react-faster",
    title: "Shipping React Faster Without Burning the Codebase",
    excerpt:
      "Lessons from rebuilding internal tooling at Harley Innovations: how component primitives, SSR and pragmatic caching cut iteration time in half.",
    date: "2026-05-21",
    readTime: "2 min read",
    category: "Engineering",
    body: [
      "When I joined the team, every new screen felt like starting from scratch. Buttons drifted, spacing wandered, and TypeScript errors lived in a folder no one opened.",
      "We did three things, in this order: extracted a small set of primitives, locked the design tokens, and moved data fetching to the server. Nothing fancy — but together they removed entire categories of bugs.",
      "Primitives first. We picked 12 components — Button, Input, Field, Card, Sheet, Dialog, Tabs, Avatar, Badge, Menu, Tooltip, Toast — and forbade ad-hoc variants in feature code. Every variant must be added to the primitive.",
      "Then tokens. Color, radius, spacing and font tokens went into one CSS file. Feature code only consumes semantic tokens (bg-card, text-muted-foreground), never raw values. That alone killed half our drift.",
      "SSR with TanStack Start gave us per-route loaders and tiny client bundles. Most pages render before JS finishes — and the few interactive bits hydrate where needed.",
      "Six weeks later, ticket throughput nearly doubled. Not because we worked harder — because the codebase stopped pushing back.",
    ],
  },
  {
    slug: "ssr-tradeoffs",
    title: "The SSR Tradeoffs Nobody Warns You About",
    excerpt:
      "SSR is great for SEO and first paint — but it changes how you think about state, auth, and analytics. Here's what I learned the slow way.",
    date: "2026-05-20",
    readTime: "1 min read",
    category: "Architecture",
    body: [
      "SSR isn't a free upgrade. It's a different runtime model — and if you treat it like a sticker you add to a Vite app, you'll hit subtle issues for weeks.",
      "Issue one: window. Anything that touches window, localStorage or document at module scope crashes on the server. Move it inside useEffect or wrap with a typeof guard.",
      "Issue two: auth. Your session cookie is on the request, not in localStorage. Loaders must read from the request context — not call a client SDK.",
      "Issue three: analytics. Page views fire on the client after hydration. Don't double-count by also firing in a server loader.",
      "Done right, SSR pays off. Done blindly, it doubles your error budget. Go in with eyes open.",
    ],
  },
  {
    slug: "design-systems-for-small-teams",
    title: "Design Systems For Small Teams (Without the Overhead)",
    excerpt:
      "You don't need a 200-component library. You need 12 components, 6 tokens, and a rule everyone respects.",
    date: "2026-05-19",
    readTime: "2 min read",
    category: "Design",
    body: [
      "The phrase 'design system' has scared a lot of small teams into doing nothing. They think it means a year-long project, a Figma library and a Storybook deploy.",
      "It doesn't. A useful system for a 3-person team is a CSS file with semantic tokens, a handful of styled primitives, and one rule: no raw hex in feature code.",
      "Start with color, spacing and radius tokens. Add a Button. Add an Input. When the third Card appears, extract it. Grow the system from real pain, not speculation.",
      "The point isn't completeness — it's consistency. Twelve components used everywhere beats two hundred used sometimes.",
    ],
  },
];

export function getPost(slug: string) {
  return posts.find((p) => p.slug === slug);
}
